[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "day_1"
path = "src/day_1/day_1.rs"

[[bin]]
name = "day_2"
path = "src/day_2/day_2.rs"

[[bin]]
name = "day_3"
path = "src/day_3/day_3.rs"

[[bin]]
name = "day_4"
path = "src/day_4/day_4.rs"

[dependencies]
